# MkDocs configuration for builds with material theme

INHERIT: mkdocs-base.yml

site_url: "https://docs.percona.com/postgresql/11/"
plugins:
  section-index: {}  # Adds links to nodes - comment out when creating PDF

theme:
  name: material
  custom_dir: _resource/overrides/

# Theme features

  features:
    - search.highlight
    - navigation.top
    - navigation.tracking
    - content.tabs.link  
 

plugins:
  - section-index # Adds links to nodes - comment out when creating PDF
  - search
  - git-revision-date

#markdown_extensions:
#  - pymdownx.tabbed:
#      alternate_style: true 


#Google Analytics configuration 
extra:
  analytics:
    provider: google
    property: UA-343802-3
