# MkDocs configuration for Netlify builds

INHERIT: mkdocs-base.yml
site_url: https://docs.percona.com/postgresql/13/index.html

theme:
  name: material
  custom_dir: _resource/overrides


#Google Analytics configuration 
extra:
  analytics:
    provider: google
    property: UA-343802-3
